CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LogiData.Web.Models
{
    // Form Model
    public class Owner
    {
        [Display(Name = "Owner ID")]
        [Required]
        public int ID { get; set; }

        [Display(Name = "Owner Name")]
        public string Name { get; set; }

        [Display(Name = "Location")]
        public string City { get; set; }

        [Display(Name = "First Year")]
        public int StartYear { get; set; }

        [Display(Name = "Paid For This Year")]
        public bool HasPaidThisYear { get; set; }

        [Display(Name = "Owner Is Replaceable")]
        public bool IsReplaceable { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Models/OwnerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LogiData.Web.Models
{
    public class OwnerViewModel
    {
        public Owner EditedOwner { get; set; }
        public List<Owner> OwnersList { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Controllers/OwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using LogiData.Web.Models;
using MyLogiscool.Logic;
using MyLogiscool.Data;
using MyLogiscool.Repository;

namespace LogiData.Web.Controllers
{
    public class OwnersController : Controller
    {
        ILogic logic;
        IMapper mapper;
        OwnerViewModel vm;

        public OwnersController()
        {
            logic = new MainLogic();
            mapper = MapperFactory.CreateMapper();
            vm = new OwnerViewModel();
            vm.EditedOwner = new Owner();
            var owners = logic.ReadAllOwners();
            vm.OwnersList = mapper.Map<IEnumerable<MyLogiscool.Data.Owners>, List<Models.Owner>>(owners);
        }

        private Owner GetOneOwner(int id)
        {
            Owners oneOwner = logic.ReadOwners(id);
            return mapper.Map<MyLogiscool.Data.Owners, Models.Owner>(oneOwner);
        }

        // GET: Owner
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("OwnerIndex", vm);
        }

        // GET: Owner/Details/5
        public ActionResult Details(int id)
        {
            return View("OwnerDetails", GetOneOwner(id));
        }

        //GET: /Owner/Remove/5
        public ActionResult Remove(int id)
        {
            //TempData["editResult"] = "Delete FAIL";
            logic.DeleteOwners(id);
            TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        // GET: /Owner/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedOwner = GetOneOwner(id);
            return View("OwnerIndex", vm);
        }

        // POST: /Owner/Edit
        [HttpPost]
        public ActionResult Edit(Owner owner, string editAction)
        {
            if (ModelState.IsValid && owner != null)
            {
                TempData["editResult"] = "Edit Ok";
                if (editAction == "AddNew")
                {
                    logic.CreateOwners(mapper.Map<Models.Owner,MyLogiscool.Data.Owners>(owner));
                }
                else
                {
                    logic.UpdateOwners(mapper.Map<Models.Owner, MyLogiscool.Data.Owners>(owner));
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedOwner = owner;
                return View("OwnerIndex", vm);
            }
        }
    }
}

CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Views/Owners/OwnerDetails.cshtml
@model LogiData.Web.Models.Owner
@{
    ViewBag.Title = "OwnerDetails";
}

<h2>Datasheet of one owner</h2>

@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>The ID of the owner</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(m => m.Name)
        </td>
        <td>
            @Html.DisplayFor(m => m.Name)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(m => m.City)
        </td>
        <td>
            @Html.DisplayFor(m => m.City)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(m => m.StartYear)
        </td>
        <td>
            @Html.DisplayFor(m => m.StartYear)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(m => m.HasPaidThisYear)
        </td>
        <td>
            @Html.DisplayFor(m => m.HasPaidThisYear)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(m => m.IsReplaceable)
        </td>
        <td>
            @Html.DisplayFor(m => m.IsReplaceable)
        </td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Views/Owners/OwnerEdit.cshtml
@model LogiData.Web.Models.Owner

<h2>Edit one owner</h2>

@using (Html.BeginForm("Edit", "Owners"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.City)</div>
    <div class="editor-field">@Html.EditorFor(m => m.City)</div>

    <div class="editor-label">@Html.LabelFor(m => m.StartYear)</div>
    <div class="editor-field">@Html.EditorFor(m => m.StartYear)</div>

    <div class="editor-label">@Html.LabelFor(m => m.HasPaidThisYear)</div>
    <div class="editor-field">@Html.EditorFor(m => m.HasPaidThisYear)</div>

    <div class="editor-label">@Html.LabelFor(m => m.IsReplaceable)</div>
    <div class="editor-field">@Html.EditorFor(m => m.IsReplaceable)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Views/Owners/OwnerIndex.cshtml
@model LogiData.Web.Models.OwnerViewModel

@{
    ViewBag.Title = "OwnerIndex";
}

<h2>Owners Index</h2>

<p style:"color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("OwnerEdit", Model.EditedOwner)

@Html.Partial("OwnerList", Model.OwnersList)

CSHARP/OENIK_PROG3_2019_1_FKAVXF/LogiData.Web/Views/Owners/OwnerList.cshtml
@model IEnumerable<LogiData.Web.Models.Owner>

<h2>List of owners</h2>

@if(Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.Name)</th>
            <th>@Html.DisplayNameFor(m => m.City)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.Name)</td>
            <td>@Html.DisplayFor(m => item.City)</td>
            <td>@Html.ActionLink("[SHOW]","Details",new { id = item.ID })</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
        </tr>
        }
    </table>
}